[install]
is_configured = false
state = enabled
build = 1

[launcher]
author = Alexandre Demeyer
description = TheHive-Cortex
version = 4.0.0

[ui]
is_visible = true
label = TheHive-Cortex
supported_themes = light,dark

[package]
id = TA-thehive-cortex
check_for_updates = true
