[install]
is_configured = 0

[launcher]
author = LetMeR00t
description = Splunk Add-on for TheHive and Cortex
version = 4.0.0

[ui]
is_visible = 1
label = TheHive-Cortex

[package]
id = TA-thehive-cortex

[id]
name = TA-thehive-cortex
version = 4.0.0
