[thehive_cases]
definition = sourcetype="thehive:last_created:cases" OR sourcetype="thehive:last_updated:cases" OR sourcetype="thehive:cases:*"
description = Macro to search across all legacy and new TheHive Cases sourcetypes

[thehive_alerts]
definition = sourcetype="thehive:last_created:alerts" OR sourcetype="thehive:last_updated:alerts" OR sourcetype="thehive:alerts:*"
description = Macro to search across all legacy and new TheHive Alerts sourcetypes

[thehive_observables]
definition = sourcetype="thehive:last_created:observables" OR sourcetype="thehive:last_updated:observables" OR sourcetype="thehive:observables:*"
description = Macro to search across all legacy and new TheHive Observables sourcetypes

[thehive_audit]
definition = sourcetype="thehive:last_created:audit" OR sourcetype="thehive:audit"
description = Macro to search across all legacy and new TheHive Audit sourcetypes

[thehive_tasks]
definition = sourcetype="thehive:last_created:case_tasks" OR sourcetype="thehive:last_updated:case_tasks" OR sourcetype="thehive:tasks:*"
description = Macro to search across all legacy and new TheHive Tasks sourcetypes
